meta_product_name: "One"
meta_title: "One - Organising the Outreach"
meta_description: "Helping to organise the outreach for the Australian bushfires."
meta_image: "homepage.png" # should exist in `app/assets/images/`
